// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Ht80WJO889deK-_eWqeV_kjr074KMoI',
    appId: '1:1001315717519:web:bb90144e0ad2413e0f3bfa',
    messagingSenderId: '1001315717519',
    projectId: 'expense-manager-c8408',
    authDomain: 'expense-manager-c8408.firebaseapp.com',
    storageBucket: 'expense-manager-c8408.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4vx9ZoJy2RHG4mE64q5RUmYVfaE8qpk',
    appId: '1:1001315717519:android:f98649fc0e250e300f3bfa',
    messagingSenderId: '1001315717519',
    projectId: 'expense-manager-c8408',
    storageBucket: 'expense-manager-c8408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWnPUDGHzRDFEJrTHpJDitoatc-25O66w',
    appId: '1:1001315717519:ios:f36559835fa55ca30f3bfa',
    messagingSenderId: '1001315717519',
    projectId: 'expense-manager-c8408',
    storageBucket: 'expense-manager-c8408.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWnPUDGHzRDFEJrTHpJDitoatc-25O66w',
    appId: '1:1001315717519:ios:f36559835fa55ca30f3bfa',
    messagingSenderId: '1001315717519',
    projectId: 'expense-manager-c8408',
    storageBucket: 'expense-manager-c8408.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Ht80WJO889deK-_eWqeV_kjr074KMoI',
    appId: '1:1001315717519:web:b94338696b48bcb80f3bfa',
    messagingSenderId: '1001315717519',
    projectId: 'expense-manager-c8408',
    authDomain: 'expense-manager-c8408.firebaseapp.com',
    storageBucket: 'expense-manager-c8408.firebasestorage.app',
  );
}
